# -*- coding: utf-8 -*-
"""Zadanie_17.10.24.ipynb

Automatically generated by Colab.

def is_criticality_balanced(temperature, neutrons):
    if temperature < 800 and neutrons > 500 and temperature*neutrons < 500000:
        return True
    else:
        return False

def reactor_efficency(voltage, current, theoretical_max_power):
    max_power = voltage * current
    efficiency = (max_power / theoretical_max_power) * 100
    if efficiency >= 80:
        return "zielone"
    elif efficiency >= 60:
        return "pomarańczowe"
    elif efficiency >= 30:
        return "czerwone"
    else:
        return "czarne"

def fail_safe(temperature, neutrons_produced_per_second, threshold):
  if temperature * neutrons_produced_per_second < threshold * 0.9:
    return "LOW"
  elif temperature * neutrons_produced_per_second < threshold * 1.1:
    return "NORMAL"
  else:
    return "DANGER"

print(reactor_efficency(1200, 5, 1000))
print(is_criticality_balanced(500, 600))
print(fail_safe(1100,500,100))
